### ISSUE TITLE
Public Quest Raven Host Vanguard Stage II stuck

### ISSUE THREAD

**Issue by Krubster** [Shmerrick/ProjectWAR#12]
Stuck at very first public quest on order side in Nordland. Second stage prompted us to protect Sigwald for a time, but I didnt notice him, and after timer expired - nothing happened, quest wont finished or failed.

**Comment by cooler-SAI** [comment]
can't reproduce! all work, tested
https://github.com/Shmerrick/ProjectWAR/commit/8ecb74d3172c3d141fed6bf95b3e3eb80ddfa3d4
