### ISSUE TITLE
Double Shot on Engineer

### ISSUE THREAD

**Issue by Krubster** [Shmerrick/ProjectWAR#14]
Dunno if it is a bug, but sometimes my engineer shots twice in target

**Comment by Shmerrick** [comment]
Can you please provide more information. When does this happen?

**Comment by Krubster** [comment]
1) Target an enemy
2) Press gun shot ability
3) After delay my character shots first time
4) After a half maybe one sec it shots second time
I think this may be client problem, I'm issuing some periodic performance and net problems. I'll try to track this issue in future

**Comment by Shmerrick** [comment]
The engineer has a ranged auto attack. If gun blasts triggers auto attack can trigger after this.

**Comment by Krubster** [comment]
oh, didnt know about it. Tbh I m not very clear know how auto attack works at all, cause if I wont press any buttons, my character stays and do nothing (On RoR, on this core I dont test this). Then i think this can be closed
