### ISSUE TITLE
Chap 1 chaos quest Pillaging

### ISSUE THREAD

**Issue by Bignusty** [Shmerrick/ProjectWAR#20]
Reward pot bugged cant be used

**Comment by wardev1** [comment]
![image](https://user-images.githubusercontent.com/64143661/101088145-21579600-35ab-11eb-91da-313cecd712af.png)

**Comment by cooler-SAI** [comment]
fixed
![image](https://user-images.githubusercontent.com/812439/165844186-3068af46-ade3-4b0e-b319-3465924544b7.png)

**Comment by cooler-SAI** [comment]
![image](https://user-images.githubusercontent.com/812439/165844257-defed91f-9316-4c9d-8f70-afa16e2eaa27.png)
