### ISSUE TITLE
Chap1 puclic quest Ruinous power

### ISSUE THREAD

**Issue by Bignusty** [Shmerrick/ProjectWAR#21]
An empire BW is missing at stage 3 whit Chaos beast if i remember

**Comment by Shmerrick** [comment]
Confirmed. BW is supposed to spawn at center and then morph into the Bloodbeast of Khorne.

Chaos CH 1 PQ - Ruinous Powers

**Comment by cooler-SAI** [comment]
all works

![image](https://user-images.githubusercontent.com/812439/169717165-e91e4abe-118a-476b-8039-af79bd246432.png)
