### ISSUE TITLE
Crashed to desktop.  User Interface/Keybinds erased.  Mouse Movement locking in place.

### ISSUE THREAD

**Issue by Wolfsiege** [Shmerrick/ProjectWAR#38]
Shortly after rolling another class to test, I imported my UI from the main one.  Within a minute or two my game crashed to desktop... No big deal... When I reloaded the game and Char.  The profile I was sharing was gone.  I logged to the Sharing character, and everything had been reset...  No big deal either, I can just remake again.  But interestingly, this time my mouse sticks when I move with it.

I left & right click to steer, and it locks, continuously turning my character, it takes a right-click to unlock it...  Somewhat jarring for a mouse turner.

However may not be game related all, just wanted to mention it incase someone else has it happen in the future.

**Comment by Wolfsiege** [comment]
Closed, relaunched, created a new character.  The mouse locking isn't an issue at the moment.

**Comment by Wolfsiege** [comment]
Another test... Logged out of game completely and relaunched... It fixed the issue.

No need to delete characters as I tried just before that.

**Comment by cooler-SAI** [comment]
can'treproduce, all works good
https://github.com/Shmerrick/ProjectWAR/commit/8ecb74d3172c3d141fed6bf95b3e3eb80ddfa3d4
