### ISSUE TITLE
Curious Barrel: Skaven Spawning in Walls

### ISSUE THREAD

**Issue by Wolfsiege** [Shmerrick/ProjectWAR#39]
As I was wandering about Altdorf, I decided to take a whack at the multiple Curious Barrels... 3 out of 4 that were broken.  Spawned the Skaven inside the walls, making them unattackable.

![image](https://user-images.githubusercontent.com/59191439/99633569-ba5fac00-2a04-11eb-9811-9ce5897ff103.png)

**Comment by cooler-SAI** [comment]
not all, 2 of 10, tested!
