### ISSUE TITLE
Loot Table

### ISSUE THREAD

**Issue by Wolfsiege** [Shmerrick/ProjectWAR#47]
I've Roamed about killing different mobs at different levels.  And it appears that regardless of level, they're all dropping level 13 - 15 gear.

**Comment by Wolfsiege** [comment]
Correction, anything below 15 will drop the appropriate level.  Example:  Level 7 mobs are dropping level 7 gear.

**Comment by Shmerrick** [comment]
There are loot group items that stop dropping if you are too high of a rank. Please give me examples of what you were killing and at what rank you were killing them.

**Comment by Shmerrick** [comment]
Issue has been resolved.
