### ISSUE TITLE
Quest ID 30056 - A Sticky Situation 

### ISSUE THREAD

**Issue by jeeron** [Shmerrick/ProjectWAR#96]
Hi :) 
Quest 30056 doesn't work. 
After clic on Gavin Scherer there is nothing.

Here is a screen: 
![galvin_scherer-30056-quest-spqwn-507](https://github.com/Shmerrick/ProjectWAR/assets/5569302/c5eddc40-2840-4fcf-9b1e-e42f607a5d0e)

**Comment by danman981** [comment]
tested and it works
